//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameNetFramework
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Label Label1;
        protected global::System.Web.UI.WebControls.Label Label6;
        protected global::System.Web.UI.WebControls.Label lblHistory;
        protected global::System.Web.UI.WebControls.Label Label5;
        protected global::System.Web.UI.WebControls.TextBox txtGuess;
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.Label lblHint;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblLastGuess;
        protected global::System.Web.UI.WebControls.Button cmdGuess;
        protected global::System.Web.UI.WebControls.Label lblSystemName;
        protected global::System.Web.UI.WebControls.Label Label4;
        protected global::System.Web.UI.WebControls.Label Label3;
    }
}
