namespace DistributedLucene.LuceneData
{
    public class ProductNameData
    {
        public static readonly string[] ProductNames = new string[]
        {
            "Chai",
            "Chang",
            "Aniseed Syrup",
            "Chef Anton's Cajun Seasoning",
            "Grandma's Boysenberry Spread",
            "Uncle Bob's Organic Dried Pears",
            "Northwoods Cranberry Sauce",
            "Ikura12",
            "Queso Cabrales",
            "Queso Manchego La Pastora",
            "Konbu",
            "Tofu",
            "Genen Shouyu",
            "Pavlova",
            "Carnarvon Tigers",
            "Teatime Chocolate Biscuits",
            "Sir Rodney's Marmalade",
            "Sir Rodney's Scones",
            "Gustaf's Knäckebröd",
            "Tunnbröd",
            "NuNuCa Nuß-Nougat-Creme",
            "Gumbär Gummibärchen",
            "Schoggi Schokolade",
            "Nord-Ost Matjeshering",
            "Gorgonzola Telino",
            "Mascarpone Fabioli",
            "Geitost",
            "Sasquatch Ale",
            "Steeleye Stout",
            "Inlagd Sill",
            "Gravad lax",
            "Côte de Blaye",
            "Chartreuse verte",
            "Boston Crab Meat",
            "Jack's New England Clam Chowder",
            "Ipoh Coffee",
            "Gula Malacca",
            "Rogede sild",
            "Spegesild",
            "Zaanse koeken",
            "Chocolade",
            "Maxilaku",
            "Valkoinen suklaa",
            "Manjimup Dried Apples",
            "Filo Mix",
            "Tourtière",
            "Pâté chinois",
            "Gnocchi di nonna Alice",
            "Ravioli Angelo",
            "Escargots de Bourgogne"
        };
    }
}
